---
name: Style Guide
on:
  push:
    branches:
      - master
      - main
      - /^release-.*$/
    tags: ["*"]
    paths:
      - "**/*.jl"
      - ".github/workflows/FormatCheck.yml"
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    paths:
      - "**/*.jl"
      - ".github/workflows/FormatCheck.yml"
jobs:
  format-check:
    name: Julia
    # These permissions are needed to:
    # - Delete old caches: https://github.com/julia-actions/cache#usage
    # - Post formatting suggestions: https://github.com/reviewdog/action-suggester#required-permissions
    permissions:
      actions: write
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - uses: julia-actions/setup-julia@4a12c5f801ca5ef0458bba44687563ef276522dd # v3.0.0
        with:
          version: "1"
      - uses: julia-actions/cache@9a93c5fb3e9c1c20b60fc80a478cae53e38618a4 # v3.0.2
      - name: Install JuliaFormatter
        shell: julia --project=@format --color=yes {0}
        run: |
          using Pkg
          Pkg.add(PackageSpec(; name="JuliaFormatter", version="1"))
      - name: Check formatting
        shell: julia --project=@format --color=yes {0}
        run: |
          using JuliaFormatter
          format(".", YASStyle(); verbose=true) || exit(1)
      # Add formatting suggestions to non-draft PRs even if when "Check formatting" fails
      - uses: reviewdog/action-suggester@aa38384ceb608d00f84b4690cacc83a5aba307ff # v1.24.0
        if: ${{ !cancelled() && github.event_name == 'pull_request' && github.event.pull_request.draft == false }}
        with:
          tool_name: JuliaFormatter
